# Generated by Django 5.1.1 on 2024-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birhumindapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subHead', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
