# Generated by Django 5.1.1 on 2024-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birhumindapp', '0004_oursuccess_userprofile_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials_images/'),
        ),
    ]
