# Generated by Django 5.1.1 on 2024-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0005_tutorial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("No Formal Education", "No Formal Education"),
                    ("Primary Education", "Primary Education"),
                    ("Secondary Education", "Secondary Education"),
                    ("Degree", "Degree"),
                    ("Master Degree", "Master Degree"),
                ],
                max_length=100,
            ),
        ),
    ]
