# Generated by Django 5.1.1 on 2024-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0006_consultancy_alter_userprofile_education_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="accessrecord",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="accessrecord",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="finance_images/"),
        ),
    ]
