# Generated by Django 5.1.1 on 2024-11-11 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0009_remove_userprofile_user_delete_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("no-formal", "No Formal Education"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("degree", "Degree"),
                            ("masterPlus", "Masters or Higher"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.RenameField(
            model_name="tutorial",
            old_name="image",
            new_name="course_image",
        ),
        migrations.RenameField(
            model_name="tutorial",
            old_name="author",
            new_name="instructor",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="is_published",
        ),
        migrations.AddField(
            model_name="tutorial",
            name="about_instructor",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorial",
            name="instructor_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="instructor_images/"
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="instructor_title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
