# Generated by Django 5.1.1 on 2024-11-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0010_userprofile_delete_newsarticle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorial",
            name="about_instructor",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="instructor_image",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="instructor_title",
        ),
    ]
