# Generated by Django 5.1.1 on 2024-11-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0013_tutorial_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpage",
            name="topic",
        ),
        migrations.DeleteModel(
            name="AccessRecord",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="WebPage",
        ),
    ]
