# Generated by Django 5.1.1 on 2024-11-12 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0014_remove_webpage_topic_delete_accessrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstofinance",
            name="url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
