# Generated by Django 5.1.1 on 2024-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0015_accesstofinance_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstofinance",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="finance_logo/"),
        ),
    ]
