# Generated by Django 5.1.1 on 2024-11-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0016_accesstofinance_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesstofinance",
            old_name="image",
            new_name="company_logo",
        ),
    ]
