# Generated by Django 5.1.1 on 2024-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0019_userprofile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsubmission",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("no-formal", "No Formal Education"),
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("degree", "Degree"),
                    ("masterPlus", "Masters or Higher"),
                ],
                max_length=20,
            ),
        ),
    ]
