# Generated by Django 5.1.1 on 2024-11-13 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0020_alter_documentsubmission_education_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubmission",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("bds", "Bds Document"),
                    ("business", "Business"),
                    ("tutorial", "Tutorial"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
