# Generated by Django 5.1.1 on 2024-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birhumindapp", "0021_documentsubmission_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubmission",
            name="selected_templates",
            field=models.JSONField(default=list),
        ),
    ]
