name: Deploy Django BirhumindApp

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Tests
        run: |
          python manage.py test

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.SSH_PRIVATE_KEY }}" ${{ secrets.SSH_USER }}@${{ secrets.VPS_IP }} << 'EOF'         
          cd /var/www/birhubackend/birhumind
          git pull origin main
          source /var/www/birhubackend/benv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn  
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
